language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

before_install:
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq

install:
  - sudo apt-get install --allow-unauthenticated -qq clang-3.5
  - pip install pep8 coveralls

script:
  - pep8 libscanbuild tests
  - python setup.py check
  - python setup.py install
  - coverage run --source=libscanbuild setup.py test

after_success:
  coveralls
