language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install pep8

script:
  - nosetests -v bin/test_*
  - pep8 bin
