language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
    packages:
      - clang-3.6

install:
  - pip install pep8 coveralls

script:
  - pep8 libear libscanbuild tests
  - python setup.py check
  - python setup.py install
  - coverage run --source=libscanbuild setup.py test

after_success:
  coveralls
