language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install:
  - pip install .
  - pip install nose
  - pip install pep8

script:
  - nosetests -v bin
  - pep8 bin
  - python setup.py build
  - python setup.py install
